#### Occurrences

### Get All Occurrences
GET http://localhost:8080/daeproject/api/occurrences
Accept: application/json

### Get Occurrence by ID
GET http://localhost:8080/daeproject/api/occurrences/1
Accept: application/json

### Update an Occurrence
PUT http://localhost:8080/daeproject/api/occurrences/1
Content-Type: application/json

{
  "description": "Occurrence 1",
  "status": "PENDING"
}

### Upload Document
POST http://localhost:8080/daeproject/api/occurrences/1/documents HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="doc1.txt"

< E:\Documents\test.txt

--boundary


#### Customers

### Get All Occurrences of a Specific Customer By NIF
GET http://localhost:8080/daeproject/api/customers/289910325/occurrences
Accept: application/json

### Create Customer
POST http://localhost:8080/daeproject/api/customers
Content-Type: application/json

{
  "nif": "289911123",
  "name": "Marisa",
  "email": "email@email.email",
  "password": "123456"
}
