#### Auth

### Login
POST http://localhost:8080/daeproject/api/auth/login
Content-Type: application/json

{
  "vat": "289910323",
  "password": "123456"
}

#### Occurrences

### Get All Occurrences
GET http://localhost:8080/daeproject/api/occurrences
Accept: application/json

### Get All Pending Occurrences
GET http://localhost:8080/daeproject/api/occurrences/pending
Accept: application/json

### Get All Approved Occurrences
GET http://localhost:8080/daeproject/api/occurrences/approved
Accept: application/json

### Get Occurrence by ID
GET http://localhost:8080/daeproject/api/occurrences/1
Accept: application/json

### Update an Occurrence
PUT http://localhost:8080/daeproject/api/occurrences/1
Content-Type: application/json

{
  "description": "Occurrence 1",
  "status": "PENDING"
}

### Approve an Occurence
PATCH http://localhost:8080/daeproject/api/occurrences/1/approve
Accept: application/json
Content-Type: application/json

{
  "expertVat": "123123123"
}


### Reject an Occurence
PATCH http://localhost:8080/daeproject/api/occurrences/5/reject
Accept: application/json
Content-Type: application/json

{
  "expertVat": "123123123"
}



### Upload Document
POST http://localhost:8080/daeproject/api/occurrences/1/documents HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyODk5MTAzMjMiLCJpYXQiOjE2NzM1NzA0MTYsImV4cCI6MTY3MzU3NDAxNn0.-d4vMsCf0x18l_haAC1jXa0ot3qvAR21tXpVpIV-hVA

--boundary
Content-Disposition: form-data; name="file"; filename="sample-3s.mp3"

< E:\Documents\sample-3s.mp3

--boundary


#### Customers

### Get All Occurrences of a Specific Customer By VAT
GET http://localhost:8080/daeproject/api/customers/289910325/occurrences
Accept: application/json

### Get All Policies of a Specific Customer By VAT
GET http://localhost:8080/daeproject/api/customers/289910325/policies
Accept: application/json

### Create Customer
POST http://localhost:8080/daeproject/api/customers
Content-Type: application/json

{
  "vat": "289911123",
  "name": "Marisa",
  "email": "email@email.email",
  "password": "123456"
}


#### Policies

### Get All Policies
GET http://localhost:8080/daeproject/api/policies
Accept: application/json

### Get A Policy By Code
GET http://localhost:8080/daeproject/api/policies/86084
Accept: application/json

### Get All Occurrences of a Policy
GET http://localhost:8080/daeproject/api/policies/86084/occurrences
Accept: application/json


#### Services

### Get All Services
GET http://localhost:8080/daeproject/api/services
Accept: application/json

### Get Services By TYpe
GET http://localhost:8080/daeproject/api/services/electronics
Accept: application/json
